### ISSUE TITLE
LOW HASHARATE

### ISSUE THREAD

**Issue by therawest** [PiTi2k5/Crypto-Webminer#23]
Hello, so the hashrate is not okay, it's 7x lower than it should be.
I've got INTEL i5 9400f =800hs/s (easy)
And I've got only 120mh/s troguh webminer.
How to fix that?

**Comment by PiTi2k5** [comment]
You should look at mining pool website for stats because of auto algo switch, most of time you mining CN-Heavy (it is lower mining speed) but more profit in xmr. If you check the mining pool you see raw hashrate and pay hashrate. https://moneroocean.stream/#/dashboard paste in your wallet after some mining time.

**Comment by PiTi2k5** [comment]
.
